name: modern-treehouse
static_sites:
  - name: modern-treehouse-site
    github:
      repo: lightbulbmomentlabs/modern-treehouse
      branch: main
      deploy_on_push: true
    output_dir: dist
    catchall_document: index.html
    error_document: index.html
    routes:
      - path: /
